services:
  filmes-app:
    build: .
    image: filmes-web
    container_name: filmes-web
    ports:
      - "8080:80"
    networks:
      - avaliacaofilmes-network

networks:
  avaliacaofilmes-network:
    driver: bridge
