version: '3.8'
services:
  avaliacaofilmes-api:
    image: williamsilvaec/avaliacaofilmes-api
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - avaliacaofilmes-network

  angular-app:
    image: williamsilvaec/avaliacaofilmes-web
    ports:
      - "8080:80"
    networks:
      - avaliacaofilmes-network

networks:
  avaliacaofilmes-network:
    driver: bridge
